name: BuildPush DockerImage

on:
  push:
    branches:
      - main

jobs:
  build-push-attempt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
       
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Connect to Tailscale
      uses: tailscale/github-action@v3
      with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          version: latest
          tags: tag:server
        
    - name: Add SSH key
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              mkdir -p /home/runner/.ssh
              # Replace example.com with the hostname of the machine
              # you're SSH-ing into
              ssh-keyscan example.com >> /home/runner/.ssh/known_hosts
              # DOKKU_SSH_KEY is the name of the repository secret
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
              chmod 600 /home/runner/.ssh/github_actions
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
              ssh-add /home/runner/.ssh/github_actions
    
    - name: Deploy to Local Server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: | 
        ssh -o StrictHostKeyChecking=no -p 3333 ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}}
        docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/productservice:late
        docker container run -d -p 8080:80 --name .netapp ${{ secrets.DOCKERHUB_USERNAME }}/productservice:late
          
        