name: BuildPush DockerImage

on:
  push:
    branches:
      - main

jobs:
  build-push-attempt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
       
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
              
        - name: Connect to Tailscale
          uses: tailscale/github-action@v1
          with:
            authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        - name: Deploy to Local Server
          run: |
              ssh -p 3333 user@${{secrets.VPS_IP}}
              docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/productservice:late
              docker container run -d -p 8080:80--name .netapp -p ${{ secrets.DOCKERHUB_USERNAME }}/productservice:late
        