name: BuildPush DockerImage

on:
  push:
    branches:
      - main

jobs:
  build-push-attempt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
       
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Connect to Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        version: latest
        tags: tag:server
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Host Key
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Set Permissions
      run: |
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts

    - name: Deploy to Local Server
      run: |
          ssh -o StrictHostKeyChecking=no -p 3333 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
              docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/productservice:late
              docker container run -d -p 8080:80 --name .netapp ${{ secrets.DOCKERHUB_USERNAME }}/productservice:late
            EOF
        