name: BuildPush DockerImage

on:
  push:
    branches:
      - main

jobs:
  build-push-attempt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
       
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          version: latest
          tags: tag:server
      - name: Deploy
        run: |
              ssh -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}
              docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
              docker container run -d -p 8080:80 --name netapp ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
      # - name: Deploy to Local Server
      #   uses: appleboy/ssh-action@v1.2.0
      #   env:
      #     PUB_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      #   with:
      #     host: ${{ secrets.VPS_IP }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     envs: PUB_KEY
      #     script: |
      #       docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
      #       docker container run -d -p 8080:80 --name netapp ${{ secrets.DOCKERHUB_USERNAME }}/productservice:latest
        
        